![imagen](./img/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden, usando numpy.

In [14]:
my_array = np.arange (10)
nuevo=my_array [(my_array%2==1)]

print (nuevo [::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [17]:
print (my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [19]:
print (my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [3]:
matrix = np.arange (1,21).reshape (4,5)
print (matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [6]:
array = matrix [:2,:2]
print (array)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [7]:
print (matrix [::2, ::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [8]:
print (matrix [:3, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [ ]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print (x [(x=="Loro")])

indices = np.where (x=="Loro") #así devuelve las posiciones en las que se cumple la condición
print (x[indices])


['Loro' 'Loro']
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [20]:
sec = np.arange (10,30).reshape (2,5,2)
print (sec)

[[[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [24]:
ceros = np.zeros (10)
print(ceros.nbytes)
ceros [3] = 1
print (ceros)

80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [ ]:
vector = np.arange (10,50)
print (vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [26]:
def distinto_cero (vector):
    indices = np.where (vector != 0)
    return vector [indices]

my_array = np.array ([1,2,0,0,4,0])
print (distinto_cero (my_array))

[1 2 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [33]:
matrix = np.random.randint (0,100,100).reshape(10,10)
print (matrix)
print (np.min (matrix))
print (np.max (matrix))

[[37 70 51 99  3 75  3 35 56 62]
 [18 36 70 93 11 32 24 37 77 16]
 [12 47 85 87 42 23 75 43 85 13]
 [ 6 60 93 60 16  2 44 45 81 73]
 [92 71 26 45 20 27  7 16 83 29]
 [12 37 83 32 73 48 84 61 63 92]
 [57 56 90 73 13 93 94 83 28 49]
 [74 98 54 24 90 99 24 13 70 56]
 [56 77 48 75 52 23 23 59 75 51]
 [ 2 14  8 72  1 57 52 46 80 51]]
1
99


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [34]:
vector = np.random.randint (0,100,30)
print (np.mean(vector))

44.86666666666667


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [49]:
my_array = np.zeros((10,10), dtype=int)
my_array [0] = 1
my_array [-1] = 1
my_array [:,0] = 1
my_array [:,-1] = 1
print (my_array)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [53]:
matrix = np.zeros ((8,8), dtype =int)
matrix [::2, 1::2] = 1
matrix [1::2, ::2] = 1
print (matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [61]:
inicio = np.array ([[0, 1], [1, 0]])
np.tile (inicio, (3,3))


array([[0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0]])

## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [75]:
matriz = np.random.randint (25, size=(5,5))
print (matriz*np.mean (matriz)/np.std (matriz))

[[ 3.32084032  4.98126048 23.24588226  0.         26.56672258]
 [34.86882339 11.62294113  1.66042016 36.52924355 39.85008387]
 [16.60420161 18.26462178 14.94378145 21.5854621   4.98126048]
 [38.18966371 18.26462178 16.60420161 16.60420161 23.24588226]
 [ 8.30210081 21.5854621  21.5854621  28.22714274 11.62294113]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [83]:
my_array = np.arange (0, 11)
other_array = np.where ((3 < my_array) & (my_array <8), -1, my_array )
print (other_array)
another = np.where ((3 < my_array) & (my_array <8), my_array*-1, my_array )
print (another)

[ 0  1  2  3 -1 -1 -1 -1  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
